### ISSUE TITLE
Получение thumbprint сертификата

### ISSUE THREAD

**Issue by niktimmans** [MaximMonakhov/crypt_signature#4]
Не хватает получения thumbprint сертификата для дальнейшей проверки корректности

**Comment by niktimmans** [comment]
Получилось сформировать через модификацию файла CryptSignature.java

`import java.security.cert.Certificate;

...


    private static final char[] HEX_ARRAY = "0123456789ABCDEF".toCharArray();
    public static String bytesToHex(byte[] bytes) {
        char[] hexChars = new char[bytes.length * 2];
        for (int j = 0; j < bytes.length; j++) {
            int v = bytes[j] & 0xFF;
            hexChars[j * 2] = HEX_ARRAY[v >>> 4];
            hexChars[j * 2 + 1] = HEX_ARRAY[v & 0x0F];
        }
        return new String(hexChars);
    }

    public JSONObject addCertificate(String path, String password) throws JSONException {
        try {
            KeyStore keyStore = openKeyStore(path, password);
            String alias = findPrivateKeyAlias(keyStore);
            X509Certificate certificate = (X509Certificate) keyStore.getCertificate(alias);
            byte[] certBytes = keyStore.getCertificate(alias).getEncoded();
            MessageDigest md = MessageDigest.getInstance("SHA-1");
            md.update(certBytes);
            JSONObject response = new JSONObject();
            response.put("success", true);
            response.put("certificate", Base64.encodeToString(certificate.getEncoded(), Base64.NO_WRAP));
            response.put("fingerprint", bytesToHex(md.digest()));
            response.put("alias", alias);
            return response;
        } catch (FileNotFoundException e) {
            return getErrorResponse("PFX файл не найден", e);
        } catch (CertificateException e) {
            return getErrorResponse("Один из сертификатов в хранилище не может быть загружен", e);
        } catch (NoSuchAlgorithmException e) {
            return getErrorResponse("Алгоритм проверки целостности не найден", e);
        } catch (NoSuchProviderException e) {
            return getErrorResponse("JCSP провайдер не найден", e);
        } catch (IOException e) {
            return getErrorResponse("Не удалось обработать контейнер при добавлении в хранилище. Проверьте правильность введенного пароля", e);
        } catch (KeyStoreException e) {
            return getErrorResponse("Не удалось получить доступ к KeyStore", e);
        } catch (NoPrivateKeyFound e) {
            return getErrorResponse("Приватный ключ, связанный с сертификатом, не найден", e);
        } catch (Exception e) {
            return getErrorResponse("Не удалось добавить сертификат в хранилище", e);
        }
    }

`

**Comment by MaximMonakhov** [comment]
Можно было получить сертификат в виде байт и в Dart.
Добавил отпечаток с 7f22962175089accd73a3bff7ec24eb3f1edf0c0.
Спасибо!
