### ISSUE TITLE
Вынести инициализацию текстового контроллера из билд метода отображения диалога

### ISSUE THREAD

**Issue by niktimmans** [MaximMonakhov/crypt_signature#5]
[В файле lib/src/ui/dialogs.dart](https://github.com/MaximMonakhov/crypt_signature/blob/94b69ca30d2d3a9e97f79d2a4dfb1f9a5161cae1/lib/src/ui/dialogs.dart#L16)

Инициализация происходит в билд методе.

В редких случаях при скрытии клавиатуры происходит ребилд окна и текстовое поле очищается, таким образом не получается ввести корректный пароль.

Нужно как-то вынести инициализацию контроллера из билд метода.

Костыльно у себя исправил так:

`Future<String?> showInputDialog(
  BuildContext context,
  String message,
  String hintText,
  TextInputType keyboardType, {
    required TextEditingController controller,
  List<TextInputFormatter>? inputFormatters,
  bool obscureText = false,
}) `

`Future<String?> askPassword(BuildContext context, String title) => showInputDialog(
        context,
        title,
        "Пароль",
        TextInputType.visiblePassword,
        obscureText: true,
    controller: TextEditingController(),
      );`

`Future<License?> setNewLicenseSheet(BuildContext context) async {
    var maskFormatter = MaskTextInputFormatter(
      mask: '#####-#####-#####-#####-#####',
      filter: {"#": RegExp('[0-9+A-Z]')},
    );
    String? newLicense = await showInputDialog(
      context,
      "Введите вашу лицензию Крипто ПРО",
      "Номер лицензии",
      TextInputType.emailAddress,
      inputFormatters: [maskFormatter],
      controller: TextEditingController(),
    );

    return newLicense != null && newLicense.isNotEmpty ? setLicense(context, newLicense) : null;
  }`

**Comment by MaximMonakhov** [comment]
У меня не удалось вызвать ребилд окна никакими способами. Так что не смог воспроизвести проблему.
Вынес контроллер в любом случае с cec72c93a5bfb4eb64f1f3d85d957c2b4ba34bb1.
